### ISSUE TITLE
[Plan] Date butoir: 2018-05-20

### ISSUE THREAD

**Issue by raphaelcoutu** [raphaelcoutu/rhpharma#5]
# Todo
- [x] Script pour associer les contraintes existantes de rhpharma-prod.azurewebsites.net
- [x] Considérer les vendredis soirs dans l'attribution des semaines
- [x] Inscrire les fins de semaine + congés FDS
- [x] Considérer les fériés (24 juin, 1er juil., etc.)
- [x] Créer les attributs (ex: 'Vacances')
- [x] Intégrer les 4 jours/sem.
- [x] Ajouter Prévoir (comme un 5 jours par semaine)
- [x] Exporter en Excel (orderBy lastname)
- [x] Ajouter concept de ConstraintTypeCriterias (ex: pas de soirs pour l'été)
- [x] Ajouter un fichier Excel de libérations selon dispo
- [x] Associer IC, CIM à un DepartmentType == 'Clinical'
- [x] Faire le Builder pour SAMI
- [x] Essayer de faire le Builder Onco
- [x] Créer un fichier de conflits
- [x] Associer les pharmaciens à leur "bons" secteurs selon la liste de Sara

# Notes
- Les 3 jours/sem. et DP seront insérés manuellement
- Demander à Sara les %/sect.
- Antico à réfléchir à la prochaine itération
- Les fins de semaines/fériés seront inscrits manuellement par Raphaël lors des tests. (Module d'ajout de shifts à créer ultérieurement)

# Dates
 * 22/05 : Validation des contraintes par gestionnaires
* 23-24/05 : Tester avec Isabelle
